const html = `<!DOCTYPE html>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.</p>
</body>`;

// async function handleRequest(request) {
//   return new Response(html, {
//     headers: {
//       'content-type': 'text/html;charset=UTF-8',
//     },
//   });
// }

addEventListener('fetch', event => {
//   return event.respondWith(handleRequest(event.request));
    console.log("event received");
    console.log(event);
});


// // Examples
// // ​​Fetch Listener
// addEventListener('fetch', event => {
//   event.respondWith(new Response('Hello world'));
// });
// // ​​Scheduled Listener
// addEventListener('scheduled', event => {
//   event.waitUntil(handleScheduled(event));
// });


// addEventListener('fetch', function (event) {
// event.respondWith(handleRequest(event.request));
// });
// async function handleRequest(request) {
// // Only GET requests work with this proxy.
// if (request.method !== 'GET') return MethodNotAllowed(request);
// return fetch(`https://example.com`);
// }
// function MethodNotAllowed(request) {
// return new Response(`Method ${request.method} not allowed.`, {
//     status: 405,
//     headers: {
//     Allow: 'GET',
//     },
// });
// }

// // Format: Service Worker
// addEventListener('fetch', event => {
//     // Proxy to origin on unhandled/uncaught exceptions
//     event.passThroughOnException();
//     throw new Error('Oops');
// });